import type { Metadata } from "next";

// Providers
import { Providers } from "./providers";
import { ThemeProvider } from "./theme-provider";

import Header from "@/libs/components/layout/Header";
import Footer from "@/libs/components/layout/Footer";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`antialiased`}>
				<Providers>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
						<div className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
							<Header />
							{children}
							<Footer />
						</div>
					</ThemeProvider>
				</Providers>
			</body>
		</html>
	);
}
